# Generated by Django 3.0.8 on 2021-02-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dni', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('history_id', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('doner', models.BooleanField(blank=True, default=False, null=True)),
                ('alcoholic', models.BooleanField(blank=True, default=False, null=True)),
                ('drinks_coffee', models.BooleanField(blank=True, default=False, null=True)),
                ('smokes', models.BooleanField(blank=True, default=False, null=True)),
                ('diseases', models.TextField(blank=True, null=True)),
                ('risk_factors', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.Person')),
            ],
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.Person')),
            ],
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='HomeLockdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('end_cause', models.CharField(blank=True, choices=[('Abortion', 'Abortion'), ('NATURAL_BIRTH', 'Natural birth'), ('Caesarean', 'Caesarean operation')], max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Woman')),
            ],
        ),
        migrations.CreateModel(
            name='CytologicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Woman')),
            ],
        ),
    ]
